### ISSUE TITLE
Network Todo

### ISSUE THREAD

**Issue by TheZoq2** [TheZoq2/ProjectHawaii#2]
- [x]  unique islands
- [ ] receive sequence done
- [x] send sequence done + new sequence
- [ ] component done message
- [x] only one sequence
- [ ] Handle notify component done in server
- [ ] Send component done
